openapi: 3.0.3
info:
  title: API de Gerenciamento de Usuários e Restaurantes
  version: 1.0.0
  description: API para gerenciamento de usuários, restaurantes e itens do cardápio.

tags:
  - name: ItemCardapio
    description: Operações relacionadas aos itens do cardápio
  - name: Restaurante
    description: Operações relacionadas aos restaurantes
  - name: TipoCozinha
    description: Dominios de tipos de cozinhas

paths:
  # Rotas Itens do Cardápio
  /item-cardapio:
    post:
      tags:
        - ItemCardapio
      summary: Criar um novo item de cardápio
      operationId: inserirItemCardapio
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemCardapioRequest'
      responses:
        '201':
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemCardapio'

    get:
      tags:
        - ItemCardapio
      summary: Buscar lista de itens do cardápio
      operationId: buscarItensCardapio
      parameters:
        - in: query
          name: nome
          schema:
            type: string
        - in: query
          name: disponibilidadeConsumoLocal
          schema:
            type: boolean
      responses:
        '200':
          description: Lista de itens do cardápio
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemCardapio'
        '404':
          description: Nenhum item encontrado

  /item-cardapio/{id}:
    patch:
      tags:
        - ItemCardapio
      summary: Atualizar item do cardápio por ID
      operationId: atualizarItemCardapio
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemCardapioRequest'
      responses:
        '204':
          description: Atualizado com sucesso
        '404':
          description: Item do cardápio não encontrado

    delete:
      tags:
        - ItemCardapio
      summary: Deletar item do cardápio por ID
      operationId: deletarItemCardapio
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      responses:
        '204':
          description: Removido com sucesso
        '404':
          description: Item do cardápio não encontrado


  # Rotas Restaurante
  /restaurantes:
    get:
      tags:
        - Restaurante
      summary: Buscar restaurantes por filtros
      description: Retorna uma lista de restaurantes de acordo com os filtros opcionais de nome, endereço e horário de funcionamento.
      operationId: buscarRestaurante
      parameters:
        - name: nome
          in: query
          required: false
          schema:
            type: string
          example: 'José'
        - name: endereco
          in: query
          required: false
          schema:
            type: string
          example: 'Rua Central, 123'
        - name: horarioFuncionamento
          in: query
          required: false
          schema:
            type: string
          example: '08:00 - 18:00'
      responses:
        '200':
          description: Lista de restaurantes encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurante'
        '204':
          description: Nenhum restaurante encontrado
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Restaurante
      summary: Criar novo restaurante
      description: Cria um novo restaurante com os dados fornecidos, incluindo o dono (usuário responsável).
      operationId: inserirRestaurante
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestauranteRequest'
      responses:
        '201':
          description: Restaurante criado com sucesso
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Restaurante ou usuário dono já existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /restaurantes/{id}:
    patch:
      tags:
        - Restaurante
      summary: Atualizar dados do restaurante
      description: Atualiza os dados de um restaurante existente identificado pelo nome do usuário do dono.
      operationId: atualizarRestaurante
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestauranteRequest'
      responses:
        '200':
          description: Restaurante atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurante'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Restaurante
      summary: Remover restaurante
      description: Remove um restaurante identificado pelo nome do usuário do dono.
      operationId: deletarRestaurante
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      responses:
        '204':
          description: Restaurante removido com sucesso
        '404':
          description: Restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /tipos-cozinha:
    post:
      tags:
        - TipoCozinha
      summary: Criar um novo tipo de cozinha
      operationId: inserirTipoCozinha
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TipoCozinha'
      responses:
        '201':
          description: Criado com sucesso

    get:
      tags:
        - TipoCozinha
      summary: Buscar lista de tipos de cozinhas
      operationId: buscarTiposCozinhas
      parameters:
        - in: query
          name: codigo
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
        - in: query
          name: descricao
          schema:
            type: string
      responses:
        '200':
          description: Tipo de cozinha encontrado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TipoCozinha'
        '404':
          description: Tipo de cozinha não encontrado
  /tipos-cozinha/{codigo}:
    patch:
      tags:
        - TipoCozinha
      summary: Atualizar tipo de cozinha por codigo
      operationId: atualizarTipoCozinha
      parameters:
        - in: path
          name: codigo
          required: true
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TipoCozinha'
      responses:
        '204':
          description: Atualizado com sucesso
        '404':
          description: Tipo de cozinha não encontrado
    delete:
      tags:
        - TipoCozinha
      summary: Deletar tipo de cozinha por codigo
      operationId: deletarTipoCozinha
      parameters:
        - in: path
          name: codigo
          required: true
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      responses:
        '204':
          description: Removido com sucesso
        '404':
          description: Tipo de cozinha não encontrado


components:
  schemas:
    codigo:
      type: string
      format: uuid
      example: '550e8400-e29b-41d4-a716-446655440000'

    descricao:
      type: string
      example: "Italiana"

    ItemCardapio:
      type: object
      properties:
        nome:
          type: string
          example: "Pizza Margherita"
        descricao:
          type: string
          example: "Pizza tradicional com molho de tomate, mussarela e manjericão"
        preco:
          type: number
          format: float
          example: 39.90
        disponibilidadeConsumoLocal:
          type: boolean
          description: "Disponibilidade para pedir apenas no restaurante"
          example: "Consumo no local"
        foto:
          type: string
          description: "Caminho da imagem do prato"
          example: "/imagens/cardapio/pizza-margherita.jpg"
      required:
        - nome
        - descricao
        - preco
        - disponibilidadeConsumoLocal
        - foto

    ItemCardapioRequest:
      type: object
      required:
        - nome
        - descricao
        - preco
        - disponibilidadeConsumoLocal
        - foto
      properties:
        nome:
          type: string
          example: "Pizza Margherita"
        descricao:
          type: string
          example: "Pizza tradicional com molho de tomate, mussarela e manjericão"
        preco:
          type: number
          format: double
          example: 39.90
        disponibilidadeConsumoLocal:
          type: boolean
          example: "Consumo no local"
        foto:
          type: string
          example: "/imagens/cardapio/pizza-margherita-nova.jpg"

    Usuario:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        nome:
          type: string
          example: "João da Silva"
        email:
          type: string
          format: email
          example: "joao@email.com"
        endereco:
          type: string
          example: "Rua das Flores, 123"
        telefone:
          type: string
          example: "+55 11 91234-5678"
      required:
        - id
        - nome
        - email
        - endereco
        - telefone

    Restaurante:
      type: object
      properties:
        nome:
          type: string
          example: "Sabor Caseiro"
        endereco:
          type: string
          example: "Av. Brasil, 456"
        tipoCozinha:
          type: string
          example: "Comida Caseira"
        horarioFuncionamento:
          type: string
          example: "10:00 - 22:00"
        usuario:
          $ref: '#/components/schemas/Usuario'
      required:
        - nome
        - endereco
        - tipoCozinha
        - horarioFuncionamento
        - usuario

    RestauranteRequest:
      type: object
      properties:
        nome:
          type: string
          example: "Sabor Caseiro"
        endereco:
          type: string
          example: "Av. Brasil, 456"
        tipoCozinha:
          type: string
          example: "Comida Caseira"
        horarioFuncionamento:
          type: string
          example: "10:00 - 22:00"
        usuario:
          $ref: '#/components/schemas/Usuario'
      required:
        - nome
        - endereco
        - tipoCozinha
        - horarioFuncionamento
        - usuario

    TipoCozinha:
      type: object
      properties:
        codigo:
          $ref: '#/components/schemas/codigo'
        descricao:
          $ref: '#/components/schemas/descricao'

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-05-14T15:42:00Z"
        status:
          type: integer
          example: 404
        error:
          type: string
          example: "Not Found"
        message:
          type: string
          example: "Recurso não encontrado"
        path:
          type: string
          example: "/restaurantes/restaurante123/itens-cardapio"
