openapi: 3.0.3
info:
  title: API de Gerenciamento de Usuários e Restaurantes
  version: 1.0.0
  description: API para gerenciamento de usuários, restaurantes e itens do cardápio.

tags:
  - name: ItensCardapio
    description: Operações relacionadas aos itens do cardápio
  - name: Restaurante
    description: Operações relacionadas aos restaurantes

paths:

  # Rotas Itens do Cardápio

  /itens-cardapio/{id}:
    get:
      tags: [ ItensCardapio ]
      summary: Buscar item do cardápio por ID (admin/debug)
      operationId: listaItensCardapioPorID
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Item encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemCardapio'

  /restaurantes/{usuario}/itens-cardapio:
    get:
      tags:
        - ItensCardapio
      summary: Listar todos os itens do cardápio de um restaurante pelo id do dono
      description: Retorna todos os itens do cardápio de um restaurante identificado pelo usuário.
      operationId: listarItensCardapio
      parameters:
        - name: usuario
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Lista de itens retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemCardapio'
        '404':
          description: Restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - ItensCardapio
      summary: Criar novo item no cardápio de um restaurante
      description: Adiciona um novo item ao cardápio de um restaurante identificado pelo usuário.
      operationId: criarItemCardapio
      parameters:
        - name: usuario
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemCardapio'
      responses:
        '201':
          description: Item criado com sucesso
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /restaurantes/{usuario}/itens-cardapio/{idItem}:
    get:
      tags:
        - ItensCardapio
      summary: Buscar item do cardápio por ID
      description: Retorna um item específico do cardápio pelo ID para um restaurante identificado pelo usuário.
      operationId: buscarItemCardapioPorId
      parameters:
        - name: usuario
          in: path
          required: true
          schema:
            type: integer
          example: 1
        - name: idItem
          in: path
          required: true
          schema:
            type: integer
          example: 101
      responses:
        '200':
          description: Item encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemCardapio'
        '404':
          description: Item ou restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      tags:
        - ItensCardapio
      summary: Atualizar item do cardápio
      description: Atualiza um item existente no cardápio de um restaurante identificado pelo usuário.
      operationId: atualizarItemCardapio
      parameters:
        - name: usuario
          in: path
          required: true
          schema:
            type: integer
          example: 1
        - name: idItem
          in: path
          required: true
          schema:
            type: integer
          example: 101
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemCardapioRequest'
      responses:
        '200':
          description: Item atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemCardapio'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Item ou restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - ItensCardapio
      summary: Remover item do cardápio
      description: Remove um item do cardápio de um restaurante identificado pelo usuário.
      operationId: deletarItemCardapio
      parameters:
        - name: usuario
          in: path
          required: true
          schema:
            type: integer
          example: 1
        - name: idItem
          in: path
          required: true
          schema:
            type: integer
          example: 101
      responses:
        '204':
          description: Item removido com sucesso
        '404':
          description: Item ou restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


  # Rotas Restaurante
  /restaurantes:
    get:
      tags:
        - Restaurante
      summary: Listar todos os restaurantes
      description: Retorna uma lista de todos os restaurantes cadastrados.
      operationId: listarRestaurantes
      responses:
        '200':
          description: Lista de restaurantes retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurante'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Restaurante
      summary: Criar novo restaurante
      description: Cria um novo restaurante com os dados fornecidos, incluindo o dono (usuário responsável).
      operationId: criarRestaurante
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestauranteRequest'
      responses:
        '201':
          description: Restaurante criado com sucesso
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Restaurante ou usuário dono já existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /restaurantes/{usuario}:
    get:
      tags:
        - Restaurante
      summary: Buscar restaurante pelo nome do usuário (dono)
      description: Retorna um restaurante pelo nome de usuário do dono.
      operationId: buscarRestaurantePorUsuario
      parameters:
        - name: usuario
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Restaurante encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurante'
        '404':
          description: Restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /restaurantes/{id}:
    patch:
      tags:
        - Restaurante
      summary: Atualizar dados do restaurante
      description: Atualiza os dados de um restaurante existente identificado pelo nome do usuário do dono.
      operationId: atualizarRestaurante
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestauranteRequest'
      responses:
        '200':
          description: Restaurante atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurante'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Restaurante
      summary: Remover restaurante
      description: Remove um restaurante identificado pelo nome do usuário do dono.
      operationId: deletarRestaurante
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: restaurante123
      responses:
        '204':
          description: Restaurante removido com sucesso
        '404':
          description: Restaurante não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:

    ItemCardapio:
      type: object
      properties:
        nome:
          type: string
          example: "Pizza Margherita"
        descricao:
          type: string
          example: "Pizza tradicional com molho de tomate, mussarela e manjericão"
        preco:
          type: number
          format: float
          example: 39.90
        disponibilidade:
          type: string
          description: "Disponibilidade para pedir apenas no restaurante"
          example: "Consumo no local"
        foto:
          type: string
          description: "Caminho da imagem do prato"
          example: "/imagens/cardapio/pizza-margherita.jpg"
      required:
        - nome
        - descricao
        - preco
        - disponibilidade
        - foto

    ItemCardapioRequest:
      type: object
      properties:
        nome:
          type: string
          example: "Pizza Margherita"
        descricao:
          type: string
          example: "Pizza tradicional com molho de tomate, mussarela e manjericão"
        preco:
          type: number
          format: float
          example: 39.90
        disponibilidade:
          type: string
          example: "Consumo no local"
        foto:
          type: string
          example: "/imagens/cardapio/pizza-margherita-nova.jpg"
      required:
        - nome
        - descricao
        - preco
        - disponibilidade
        - foto

    Usuario:
      type: object
      properties:
        nome:
          type: string
          example: "João da Silva"
        email:
          type: string
          format: email
          example: "joao@email.com"
        endereco:
          type: string
          example: "Rua das Flores, 123"
        telefone:
          type: string
          example: "+55 11 91234-5678"
        usuario:
          type: string
          example: "joaosilva123"
      required:
        - nome
        - email
        - endereco
        - telefone
        - usuario

    Restaurante:
      type: object
      properties:
        nome:
          type: string
          example: "Sabor Caseiro"
        endereco:
          type: string
          example: "Av. Brasil, 456"
        tipoCozinha:
          type: string
          example: "Comida Caseira"
        horarioFuncionamento:
          type: string
          example: "10:00 - 22:00"
        dono:
          $ref: '#/components/schemas/Usuario'
      required:
        - nome
        - endereco
        - tipoCozinha
        - horarioFuncionamento
        - dono

    RestauranteRequest:
      type: object
      properties:
        nome:
          type: string
          example: "Sabor Caseiro"
        endereco:
          type: string
          example: "Av. Brasil, 456"
        tipoCozinha:
          type: string
          example: "Comida Caseira"
        horarioFuncionamento:
          type: string
          example: "10:00 - 22:00"
        dono:
          $ref: '#/components/schemas/Usuario'
      required:
        - nome
        - endereco
        - tipoCozinha
        - horarioFuncionamento
        - dono

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-05-14T15:42:00Z"
        status:
          type: integer
          example: 404
        error:
          type: string
          example: "Not Found"
        message:
          type: string
          example: "Recurso não encontrado"
        path:
          type: string
          example: "/restaurantes/restaurante123/itens-cardapio"
